name: env_ecommerce_seg
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26
  - pandas=2.1
  - scikit-learn=1.4
  - matplotlib=3.8
  - seaborn=0.13
  - plotly=5.18
  - scipy=1.11
  - jupyter=1.0
  - openpyxl=3.1
  - pip
  - pip:
    - yellowbrick==1.5
    - streamlit==1.31
